services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8100:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links: 
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: exemplo
    ports:
      - "8101:5432"
    
#docker compose up -d  docker compose stop e docker compose down